/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#define USE_STDPERIPH_DRIVER //使用标准外设库
#define USE_FULL_ASSERT //使用断言
#include "stm32f10x.h"
#include "stm32f10x_it.h"
#include "led.h"
#include "exti.h"
#include "delay.h"
#include "usart.h"
#include "st7735_soft.h"

void delay(__IO uint32_t nCount){

    for(; nCount != 0; nCount--);
}
void assert_failed(uint8_t* file, uint32_t line){
    //assert failed will be execute
    //printf("\r\nERROR:输入参数错误,错误文件=%s,错误行号=%s",file,line);
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
    GPIOA->CRH &= (uint32_t)0xFFFFFFF0;
    GPIOA->CRH |= (uint32_t)0x00000003;
    GPIOA->ODR |= (uint16_t)0x0100;
    //GPIOA->ODR &= (uint16_t)0xFEFF;
    for(int i=0;i<20;i++){
        GPIOA->ODR &= ~((uint16_t)0x0100);
        delay(500000);
        GPIOA->ODR |= (uint16_t)0x0100;
        delay(500000);
    }
}

int main(void)
{
    NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);
    usart_pa9_10_config();
    LCD_GPIO_Config();
    LCD_init();
    LCD_clear(BLACK);
    led_init(LED_GPIOA,LED_GPIO_PIN_8);
	while(1){
        delay_ms(1000);
        ledoff();
        delay_ms(1000);
        ledon();
        usart_sendstring(USART1,"hello world\n");
        LCD_showString(1,1,"hello world",BLUE);
        delay_ms(5000);
        LCD_clear(BLACK);
    }
}